# Makefile initially generated by claude.ai. Heavily edited (fixed) by Tadhg McDonald-Jensen

# Makefile — Arduino Nano (ATmega328P) sketch compiler
#
# Compiles your .ino sketch against the Arduino AVR core for error checking,
# and optionally produces a .hex ready to flash.
#
# Usage:
#   guix shell --manifest=manifest.scm  # on guix system aquires build dependencies automatically
#   make                  # compile-check only (default)
#   make hex              # produce a flashable .hex
#   make clean            # remove build artefacts
#   make flash PORT=/dev/ttyUSB0   # flash via avrdude (requires hex first)
#
# ── Project settings ────────────────────────────────────────────────────────
# Name of your main .ino file (without extension)
SKETCH      := DozClock

# Path to the Arduino AVR core, as downloaded by arduino-cli.
# Adjust the version number if yours differs.
# Run: ls ~/.arduino15/packages/arduino/hardware/avr/
CORE_DIR    := $(HOME)/.arduino15/packages/arduino/hardware/avr/1.8.8

LCD_DIR     ?= ./LiquidCrystal_I2C
DATETIME_DIR ?= ./DateTimeFunctions/src

# Any extra libraries your sketch uses, e.g.:
#   EXTRA_INCLUDES := -I$(CORE_DIR)/libraries/Wire/src \
#                     -I$(HOME)/.arduino15/libraries/SomeLib/src
EXTRA_INCLUDES := -I$(CORE_DIR)/libraries/Wire/src -I$(LCD_DIR) -I. -I$(DATETIME_DIR)

# ── Board settings (Arduino Nano, ATmega328P, 16 MHz) ───────────────────────
MCU         := atmega328p
F_CPU       := 16000000UL
VARIANT     := eightanaloginputs   # Nano variant in ArduinoCore-avr

# Arduino IDE version string embedded in the binary (cosmetic)
ARDUINO_VER := 10819

# ── Toolchain ────────────────────────────────────────────────────────────────
CXX         := avr-g++
CC          := avr-gcc
OBJCOPY     := avr-objcopy
SIZE        := avr-size

# ── Compiler flags ───────────────────────────────────────────────────────────
COMMON_FLAGS := \
    -mmcu=$(MCU) \
    -DF_CPU=$(F_CPU) \
    -DARDUINO=$(ARDUINO_VER) \
    -DARDUINO_AVR_NANO \
    -DARDUINO_ARCH_AVR \
    -DUSE_TIMING_FOR_INACCURATE_RESONATOR \
    -I$(CORE_DIR)/cores/arduino \
    -I$(CORE_DIR)/variants/$(VARIANT) \
    $(EXTRA_INCLUDES) \
    -Os \
    -Wall \
    -Wextra \
    -Wpedantic \
    -Wconversion \
    -ffunction-sections \
    -fdata-sections \
    -flto

CXXFLAGS    := $(COMMON_FLAGS) -std=gnu++11 -fno-exceptions -fno-threadsafe-statics
CFLAGS      := $(COMMON_FLAGS) -std=gnu11

# ── Build artefacts ──────────────────────────────────────────────────────────
BUILD_DIR   := build
SKETCH_CPP  := $(BUILD_DIR)/$(SKETCH).cpp
SKETCH_OBJ  := $(BUILD_DIR)/$(SKETCH).o
ELF         := $(BUILD_DIR)/$(SKETCH).elf
HEX         := $(BUILD_DIR)/$(SKETCH).hex

# Core source files (compiled only when building .hex / .elf)
CORE_C_SRCS   := $(wildcard $(CORE_DIR)/cores/arduino/*.c)
CORE_CXX_SRCS := $(wildcard $(CORE_DIR)/cores/arduino/*.cpp)
CORE_OBJS     := $(patsubst $(CORE_DIR)/cores/arduino/%.c,  $(BUILD_DIR)/core/%.o, $(CORE_C_SRCS)) \
                 $(patsubst $(CORE_DIR)/cores/arduino/%.cpp,$(BUILD_DIR)/core/%.o, $(CORE_CXX_SRCS))

# ── Libraries ─────────────────────────────────────────────────────────────────
# Grab both .cpp and .c, including utility/ subdirectories
LIB_CXX_SRCS := $(shell find $(CORE_DIR)/libraries -name '*.cpp')
LIB_C_SRCS   := $(shell find $(CORE_DIR)/libraries -name '*.c')

# e.g. libraries/Wire/src/utility/twi.c -> build/libs/Wire/src/utility/twi.o
LIB_CXX_OBJS := $(patsubst $(CORE_DIR)/%,$(BUILD_DIR)/libs/%,$(LIB_CXX_SRCS:.cpp=.o))
LIB_C_OBJS   := $(patsubst $(CORE_DIR)/%,$(BUILD_DIR)/libs/%,$(LIB_C_SRCS:.c=.o))
LIB_OBJS     := $(LIB_CXX_OBJS) $(LIB_C_OBJS)

# Compile rules — preserve the full relative path so there are no filename collisions
$(BUILD_DIR)/libs/%.o: $(CORE_DIR)/%.cpp | $(BUILD_DIR)
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -I$(dir $<) -c $< -o $@

$(BUILD_DIR)/libs/%.o: $(CORE_DIR)/%.c | $(BUILD_DIR)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -I$(dir $<) -c $< -o $@
# Compile rule for specifically liquicd crypstal one
$(BUILD_DIR)/libs/LiquidCrystal_I2C.o: $(LCD_DIR)/LiquidCrystal_I2C.cpp | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/libs
	$(CXX) $(CXXFLAGS) -I$(dir $<) -c $< -o $@
$(BUILD_DIR)/libs/DateTimeFunctions.o: $(DATETIME_DIR)/DateTimeFunctions.cpp | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/libs
	$(CXX) $(CXXFLAGS) -I$(dir $<) -c $< -o $@

$(BUILD_DIR)/%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# ── Default target: compile-check only ───────────────────────────────────────
.PHONY: all check hex clean flash

all: check

## check — preprocess the .ino and compile it; stops at object file.
## This is the fastest way to catch syntax / type errors without linking.
check: $(BUILD_DIR) $(SKETCH_OBJ)
	@echo ""
	@echo "✔  Compile check passed: $(SKETCH).ino"

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR) $(BUILD_DIR)/core

# Step 1: wrap the .ino in the minimal Arduino boilerplate
$(SKETCH_CPP): $(SKETCH).ino | $(BUILD_DIR)
	@echo "→  Preprocessing $(SKETCH).ino"
	@echo '#include <Arduino.h>' >  $@
	@cat $(SKETCH).ino          >> $@

# Step 2: compile to an object file (no link)
$(SKETCH_OBJ): $(SKETCH_CPP) RunMode.cpp SetMode.cpp commonFuncs.cpp
	@echo "→  Compiling $(SKETCH_CPP)"
	$(CXX) $(CXXFLAGS) -c $< -o $@

# ── hex target: full build ────────────────────────────────────────────────────
hex: $(HEX)
	$(SIZE) --mcu=$(MCU) --format=avr $(ELF)

# Compile individual Arduino core .c files
$(BUILD_DIR)/core/%.o: $(CORE_DIR)/cores/arduino/%.c | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/core
	$(CC) $(CFLAGS) -c $< -o $@

# Compile individual Arduino core .cpp files
$(BUILD_DIR)/core/%.o: $(CORE_DIR)/cores/arduino/%.cpp | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/core
	$(CXX) $(CXXFLAGS) -c $< -o $@



# Link everything into an ELF
$(ELF): $(SKETCH_OBJ) $(CORE_OBJS) $(LIB_OBJS) $(BUILD_DIR)/libs/LiquidCrystal_I2C.o
	@echo "→  Linking"
	$(CC) -mmcu=$(MCU) -Os -flto -fuse-linker-plugin \
	    -Wl,--gc-sections \
	    -o $@ $^

# Convert ELF → Intel HEX
$(HEX): $(ELF)
	@echo "→  Generating $@"
	$(OBJCOPY) -O ihex -R .eeprom $< $@

# ── flash target ──────────────────────────────────────────────────────────────
# Default port; override with: make flash PORT=/dev/ttyUSB1
PORT ?= /dev/ttyUSB0

flash: $(HEX)
	avrdude -c arduino -p $(MCU) -P $(PORT) -b 115200 \
	    -U flash:w:$(HEX):i

# ── clean ─────────────────────────────────────────────────────────────────────
clean:
	rm -rf $(BUILD_DIR)
